version: '3.8'
services:
  mercado_livre_api_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: mercado_livre_api_db
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=mercado_livre_api_db
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql-volume:/var/lib/mysql
volumes:
  mysql-volume: