server:
  port: 8080
spring:
  application:
    name: mercado_livre_api
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/mercado_livre_api_db?createDatabaseIfNotExist=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: password

ecommerce:
  jwt:
    secret: 99447632d2bfbc54519f409df043679231e08e4b
    expiration: 86400000

link:
  fake: http://bucket.io/
